#!/bin/bash

#SBATCH --job-name=pp_CCLM 
#SBATCH --nodes=1
#SBATCH --ntasks=96
#SBATCH --tasks-per-node 96
#SBATCH -t 00:30:00
#SBATCH --account=mvkkarst
#SBATCH -p standard96
#SBATCH --distribution=block,Pack

export SLURM_CPU_BIND=none

